export interface Task {
  id: string;
  title: string;
  completed: boolean;
}

export interface Project {
  id: string;
  title: string;
  description: string;
  status: "planning" | "in_progress" | "completed" | "archived";
  source: "ai_studio" | "external";
  tags: string[];
  tasks: Task[];
  links: {
    github?: string;
    deploy?: string;
    design?: string;
    workspace?: string;
  };
  notes?: string;
  createdAt: string;
  updatedAt: string;
  // Suggested roadmap generated by Gemini
  aiRoadmap?: {
    tasks: { title: string; description: string }[];
    technologies: string[];
    difficulty: string;
    timeEstimate: string;
    copilotTips: string;
    generatedAt: string;
  };
}

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "project-hub",
    title: "Project Hub (Este App)",
    description: "Plataforma minimalista e inteligente para a organização centralizada de projetos pessoais, acadêmicos e do AI Studio, com mentoria de tarefas por inteligência artificial.",
    status: "completed",
    source: "ai_studio",
    tags: ["Next.js", "Tailwind CSS", "Gemini API", "TypeScript"],
    tasks: [
      { id: "ph-1", title: "Definir paleta de cores minimalista (Off-white & Charcoal)", completed: true },
      { id: "ph-2", title: "Implementar rotas de API do Gemini para mentor de projetos", completed: true },
      { id: "ph-3", title: "Criar gerenciador de estado local reativo no localStorage", completed: true },
      { id: "ph-4", title: "Estruturar visualizações Kanban, Lista e Grid Bento", completed: true },
      { id: "ph-5", title: "Adicionar funcionalidade de Backup (Importar/Exportar JSON)", completed: true },
    ],
    links: {
      github: "https://github.com",
      deploy: "https://ai.studio/build",
      workspace: "https://ai.studio",
    },
    notes: "O Project Hub foi desenvolvido para consolidar todos os projetos em desenvolvimento em um único espaço. \n\nIdéia futura: Adicionar gráficos de progresso semanal e filtros mais profundos de tags.",
    createdAt: "2026-07-01T10:00:00Z",
    updatedAt: "2026-07-06T08:00:00Z",
  },
  {
    id: "eco-market",
    title: "E-Commerce de Plantas Ornamentais",
    description: "Uma loja online com catálogo dinâmico de plantas, dicas de cultivo personalizadas, carrinho persistente e checkout integrado de maneira minimalista.",
    status: "in_progress",
    source: "external",
    tags: ["React", "Node.js", "PostgreSQL"],
    tasks: [
      { id: "em-1", title: "Modelar banco de dados de produtos e usuários", completed: true },
      { id: "em-2", title: "Desenvolver a interface responsiva do catálogo de plantas", completed: true },
      { id: "em-3", title: "Implementar o sistema de carrinho de compras persistente", completed: false },
      { id: "em-4", title: "Configurar gateway de pagamentos (Stripe/Pix)", completed: false },
    ],
    links: {
      github: "https://github.com/exemplo/eco-market",
    },
    notes: "Preciso pesquisar APIs de envio/frete para cálculo dinâmico de prazos com base no CEP. Plantas exigem cuidados especiais no transporte.",
    createdAt: "2026-06-15T14:30:00Z",
    updatedAt: "2026-07-04T11:20:00Z",
  },
  {
    id: "ai-slides",
    title: "Gerador de Slides por IA",
    description: "Um assistente inteligente que recebe um tema livre ou arquivo de texto e gera uma estrutura completa de tópicos e design para apresentações profissionais instantâneas.",
    status: "planning",
    source: "external",
    tags: ["Python", "Gemini API", "FastAPI"],
    tasks: [
      { id: "as-1", title: "Definir engenharia de prompt para gerar tópicos coerentes", completed: false },
      { id: "as-2", title: "Pesquisar bibliotecas para conversão em formato PowerPoint (.pptx)", completed: false },
      { id: "as-3", title: "Projetar a interface de visualização prévia dos slides gerados", completed: false },
    ],
    links: {
      design: "https://figma.com",
    },
    notes: "A principal dor que esse app resolve é a procrastinação ao iniciar uma nova apresentação do zero.",
    createdAt: "2026-07-05T09:15:00Z",
    updatedAt: "2026-07-05T09:15:00Z",
  },
];
